### ISSUE TITLE
Beaker notebook home page has dead links to this repo

### ISSUE THREAD

**Issue by BrenBarn** [twosigma/beaker-notebook-archive#1]
The "getting started" page has links (such as the "using a pre-existing python" link) to a wiki on this repo that apparently no longer exists.  What happened to the wiki?  Where should users go to get that information?

**Comment by scottdraves** [comment]
The wiki moved here: https://github.com/twosigma/beakerx/wiki

The website will be updated/replaced soon.

**Comment by BrenBarn** [comment]
Some of the links on that wiki are still dead links to the old wiki.

**Comment by scottdraves** [comment]
thanks, but it will all be replaced soon, it's not worth fixing.
